def generate_article(title, content):
    # Logic to generate an article based on the title and content
    article = f"Article Title: {title}\n\n{content}\n\n---\n\nThis article was generated by the AI agent."
    return article

def generate_summary(text):
    # Logic to generate a summary of the provided text
    summary = text[:min(100, len(text))] + '...' if len(text) > 100 else text
    return f"Summary: {summary}"